package com.nspawnmgr.domain;

public enum AuditAction {
    CREATED, UPDATED, ACTIVATED, DEACTIVATED, DELETED,
    APPROVED, DENIED,
    STARTED, STOPPED, FORCE_STOPPED, RESTARTED, PAUSED, RESUMED,
    SHARED, UNSHARED,
    SESSION_STARTED,
    RAN, ABORTED
}
